version: '3.8'

services:
  caddy:
    build:
      context: ./dockerfile
      dockerfile: .caddy
    container_name: caddy
    #image: caddy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - caddy-network
    volumes:
      - /data/caddy/data/:/data/
      - /data/caddy/config/:/config/
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ekuper_app:/srv

volumes:
  ekuper_app:
    external: true

networks:
  caddy-network:
    name: caddy-network