version: '3.8'

services:
  caddy:
    build:
      context: ./dockerfile
      dockerfile: caddy
    container_name: caddy
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - caddy-network
    volumes:
      - /data/caddy/data/:/data/
      - /data/caddy/config/:/config/
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile

networks:
  caddy-network:
    name: caddy-network