services:
  caddy:
    build:
      context: ./dockerfile
      dockerfile: caddy
    container_name: caddy
    restart: unless-stopped
    #image: caddy
    ports:
      #- "2019:2019"
      - "80:80"
      - "443:443"
    networks:
      caddy-network:
      wg-network:
        ipv4_address: 10.0.0.4
    volumes:
      - /data/caddy/data/:/data/
      - /data/caddy/config/:/config/
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile

networks:
  caddy-network:
    name: caddy-network
  wg-network:
    external: true