services:
  filegator:
    container_name: filegator
    image: filegator/filegator
    restart: always
    # ports:
    #   - "8080:8080"
    volumes:
      - ~/files:/var/www/filegator/repository
    networks:
      caddy-network:

networks:
  caddy-network:
    external: true