services:
  filegator:
    container_name: filegator
    image: filegator/filegator
    restart: unless-stopped
    # ports:
    #   - "8080:8080"
    volumes:
      - /data/filegator:/var/www/filegator/repository
    networks:
      caddy-network:

networks:
  caddy-network:
    external: true