version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    # ports:
      # - 3000:3000
    volumes:
      - /data/homepage/config:/app/config
      - /data/homepage/images:/app/public/images
      - /data/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      wg-network:
networks:
  wg-network:
    external: true