services:
  wg-easy:
    environment:
      - WG_HOST=103.175.216.201

      # Optional:
      - PASSWORD=Z%xCWik2#YF2^i
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=10.0.0.3
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=10.8.0.0/24, 10.0.0.0/24
      #- WG_ALLOWED_IPS=0.0.0.0/0, ::/0
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_PRE_UP=iptables -A FORWARD -i eth0 -o wg0 -p tcp --syn --dport 7000 -m conntrack --ctstate NEW -j ACCEPT;iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 7000 -j DNAT --to-destination 10.8.0.2;iptables -t nat -A POSTROUTING -o wg0 -p tcp --dport 7000 -d 10.8.0.2 -j SNAT --to-source 10.8.0.1;
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    volumes:
      - /data/wg-easy:/etc/wireguard
    ports:
      - "51821:51821/tcp"
      - "51820:51820/udp"
      - "7000:7000"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-network:
        ipv4_address: 10.0.0.2

networks:
  wg-network:
    name: wg-network
    ipam:
      config:
      - subnet: 10.0.0.0/24