---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: Dashboard

background: 
  image: /images/background.jpg
  opacity: 70

cardBlur: xl

theme: dark

color: slate

useEqualHeights: true

disableCollapse: true

layout:
  HomeLab:
    style: row
    columns: 3
  Service:
    style: col
  Apps:
    style: col